name: Increase the resource quota
description: Report a bug encountered while operating Kubernetes
labels: kind/bug
title: Increase the resource quota for
body:
  - type: input
    id: application
    attributes:
      label: Application Name
    validations:
      required: true
  - type: input
    id: namespace
    attributes:
      label: Namespace
    validations:
      required: true
  - type: input
    id: cluster
    attributes:
      label: Cluster
    validations:
      required: true
