name: Increase the resource quota for {{application}} 
description: Report a bug encountered while operating Kubernetes
labels: kind/bug
body:
  - type: textarea
    id: application
    attributes:
      label: Application Name
    validations:
      required: true
  - type: textarea
    id: namespace
    attributes:
      label: Namespace
    validations:
      required: true
  - type: textarea
    id: cluster
    attributes:
      label: Cluster
    validations:
      required: true
